name = "agrinode"
main = "worker/index.js"
compatibility_date = "2025-04-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[observability.logs]
enabled = true
invocation_logs = true
persist = true

[[d1_databases]]
binding = "agrinode_db"
database_name = "agrinode-db"
database_id = "55ed32bb-cba9-4af8-a041-ca047c7ef344"